# Generated by Django 6.0.2 on 2026-03-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_plain',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('vendor_owner', 'Vendor Owner'), ('vendor_employee', 'Vendor Employee')], default='admin', max_length=20),
        ),
    ]
