# Generated by Django 6.0.2 on 2026-03-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='after_photo_taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worklog',
            name='before_photo_taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
