# Generated by Django 6.0.2 on 2026-03-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_worklog_approval_status_worklog_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='activityoccurrence',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('missed', 'Missed')], default='pending', max_length=20),
        ),
    ]
