# Generated by Django 6.0.2 on 2026-03-11 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activityoccurrence_assigned_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityoccurrence',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='activityoccurrence',
            name='assigned_to',
        ),
        migrations.CreateModel(
            name='OccurrenceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_assignments', to=settings.AUTH_USER_MODEL)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='activities.activityoccurrence')),
            ],
            options={
                'unique_together': {('occurrence', 'employee')},
            },
        ),
        migrations.AddField(
            model_name='activityoccurrence',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_occurrences', through='activities.OccurrenceAssignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
