# Generated by Django 6.0.3 on 2026-03-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_remove_activityoccurrence_assigned_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='payment_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('contract', 'Contract')], default='contract', max_length=20),
        ),
    ]
