# Generated by Django 6.0.3 on 2026-03-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_remove_hourly_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityoccurrence',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityoccurrence',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worklog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worklog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
