# Generated by Django 6.0.2 on 2026-03-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_add_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='payment_type',
            field=models.CharField(choices=[('contract', 'Contract'), ('daily', 'Daily Wage'), ('per_occurrence', 'Per Occurrence')], default='contract', max_length=20),
        ),
    ]
