# Generated by Django 6.0.2 on 2026-03-11 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_alter_activity_payment_type'),
        ('payments', '0003_add_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='actual_amount_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='expected_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='receipt',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='payment',
                    name='activity',
                    field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='activities.activity'),
                ),
            ],
            database_operations=[],
        ),
        migrations.CreateModel(
            name='PaymentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='payment_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payments.payment')),
            ],
            options={
                'verbose_name_plural': 'payment entries',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
